-- DropForeignKey
ALTER TABLE "Npc" DROP CONSTRAINT "Npc_mapId_fkey";

-- AlterTable
ALTER TABLE "Npc" ALTER COLUMN "mapId" DROP NOT NULL,
ALTER COLUMN "x" SET DEFAULT 0,
ALTER COLUMN "y" SET DEFAULT 0;

-- AddForeignKey
ALTER TABLE "Npc" ADD CONSTRAINT "Npc_mapId_fkey" FOREIGN KEY ("mapId") REFERENCES "Map"("id") ON DELETE SET NULL ON UPDATE CASCADE;
